Deactivate pico in schedule (#49)

diff --git a/.github/workflows/schedule.yaml b/.github/workflows/schedule.yaml
--- a/.github/workflows/schedule.yaml
+++ b/.github/workflows/schedule.yaml
@@ -76,19 +76,19 @@ jobs:
                --data '{"ref":"master","inputs":{"ubuntuVersion":"${{ matrix.ubuntuVersion }}"}}'
         env:
           GHCR_IO_TOKEN: ${{secrets.ghcr_io_token}}
-      - name: Dispatch to ghcr.io/gp-devenv/gp-pico-devenv repository
-        if: success() || failure()
-        run: |
-          curl -X POST \
-               -H "Authorization: Bearer $GHCR_IO_TOKEN" \
-               -H "X-Github-Api-Version: 2022-11-28" \
-               -H "Content-Type: application/json" \
-               https://api.github.com/repos/gp-devenv/gp-pico-devenv/actions/workflows/dispatch.yaml/dispatches \
-               --data '{"ref":"master","inputs":{"ubuntuVersion":"${{ matrix.ubuntuVersion }}"}}'
-        env:
-          GHCR_IO_TOKEN: ${{secrets.ghcr_io_token}}
+      # - name: Dispatch to ghcr.io/gp-devenv/gp-pico-devenv repository
+      #   if: success() || failure()
+      #   run: |
+      #     curl -X POST \
+      #          -H "Authorization: Bearer $GHCR_IO_TOKEN" \
+      #          -H "X-Github-Api-Version: 2022-11-28" \
+      #          -H "Content-Type: application/json" \
+      #          https://api.github.com/repos/gp-devenv/gp-pico-devenv/actions/workflows/dispatch.yaml/dispatches \
+      #          --data '{"ref":"master","inputs":{"ubuntuVersion":"${{ matrix.ubuntuVersion }}"}}'
+      #   env:
+      #     GHCR_IO_TOKEN: ${{secrets.ghcr_io_token}}
       - name: Dispatch to ghcr.io/gp-devenv/gp-ncs-devenv repository
-        if: success() || failure()
+        if: (success() || failure()) && matrix.ubuntuVersion != '26.04'
         run: |
           curl -X POST \
                -H "Authorization: Bearer $GHCR_IO_TOKEN" \
